# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebayAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=50)),
            ],
        ),
    ]
